config: improve start-dev script
- restore database
- start backend & frontend
- handle process to finish all on exit

diff --git a/start-dev b/start-dev
--- a/start-dev
+++ b/start-dev
@@ -1,4 +1,16 @@
-#!/bin/sh
+#!/bin/bash
+
+pids=( )
+
+# define cleanup function
+cleanup() {
+  for pid in "${pids[@]}"; do
+    kill -0 "$pid" && kill "$pid" # kill process only if it's still running
+  done
+}
+
+# and set that function to run before we exit, or specifically when we get a SIGTERM
+trap cleanup EXIT TERM
 
 echo "\n[JAVA]:"
 java -version  
@@ -15,5 +27,14 @@ mvn -version
 echo "\n[START POSTGRES]:"
 sudo /etc/init.d/postgresql start
 
-echo "\n[TRYING CREATE DB]:"
+echo "\n[RESTORE DB]:"
+dropdb npc
 createdb npc
+psql -d npc -f data.sql
+
+echo "\n[START SPRING AND VITE]:"
+
+mvn spring-boot:run & pids+=( "$!" )
+cd ui && npm run dev & pids+=( "$!" )
+
+wait # sleep until all background processes have exited, or a trap fires
